"""add gps_readings table

Revision ID: f01b9fdc8683
Revises: 6992040811b1
Create Date: 2026-06-30 17:15:14.448570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01b9fdc8683'
down_revision: Union[str, None] = '6992040811b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gps_readings_id'), 'gps_readings', ['id'], unique=False)
    op.create_index(op.f('ix_gps_readings_recorded_at'), 'gps_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_gps_readings_vehicle_id'), 'gps_readings', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gps_readings_vehicle_id'), table_name='gps_readings')
    op.drop_index(op.f('ix_gps_readings_recorded_at'), table_name='gps_readings')
    op.drop_index(op.f('ix_gps_readings_id'), table_name='gps_readings')
    op.drop_table('gps_readings')
    # ### end Alembic commands ###
